modLoader="javafml" #mandatory

loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All Rights Reserved"

issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/geetar/issues" #optional

[[mods]] #mandatory

modId="geetar" #mandatory

version="0.0.2" #mandatory

displayName="Geetar" #mandatory

displayURL="https://www.curseforge.com/minecraft/mc-mods/geetar" #optional

logoFile="geetar_logo.png" #optional

credits="Special thanks to Fedpulse for designing the guitar!" #optional

authors="allkillernofiller (Killer_Playz)" #optional

description='''
Adds a playable guitar to the game!
'''

[[dependencies.guitar]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.guitar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
